#!/bin/sh

PLAYER=playmusic
DAEMON=musicbox-daemon
PID_FILE=/var/run/${DAEMON}.pid

case "${1}" in
    start)
        start-stop-daemon -S -b -m -p ${PID_FILE} ${DAEMON}
        ;;
    stop)
        pkill -9 ${PLAYER}
        ;;
    *)
        exit 1
        ;;
esac
